### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by aojea** [google/dranet#21]
- [ ] Documentation: How to install it
- [ ] Codelabs: AI ML, PSC, macvlan, IDS (traffic interception) , 
- [ ] Provide Configuration: allow to set up interface characteristics as rate limiting
- [ ] Tests
- [ ] ....

**Comment by aojea** [comment]
I will move to a per issue request, so feel free to open new issues for features you want or things you miss
